version: "3"

services:
  nest:
    build: ./
    working_dir: /app
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306